title: TIIME
email: office@identinetics.com
description: >
  Trust and Internet Identity Meeting Europe
baseurl: "/wwwTiimeworkshopEu" # the subpath of your site, e.g. /blog
url: "https://identinetics.github.io" # the base hostname & protocol for your site

# Footer Settings
credit: Theme by <a href="https://themehall.com/">ThemeHall</a>

exclude:
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      use_jumbotron: "yes"
      show_on_menu: "yes"
      show_title: "yes"
